spring:
  profiles:
    active: local

#  application:
#    name: course-service
#
#server:
#  port: 8181
#
#  datasource:
#    url: jdbc:mysql://localhost:3306/course
#    username: spring
#    password: spring
#    driver-class-name: com.mysql.cj.jdbc.Driver