server:
  port: 0

spring:
  application:
    name: post-service


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
      instance:
        instance-id: ${spring.cloud.client.ip-address}:${spring.application.instance_id:${random.value}}


logging:
  level:
    root: INFO
    com:
      playdata:
        userservice:
          common: DEBUG
