server:
  port: 0

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/msaproject?serverTimezone=Asia/Seoul
    username: spring
    password: spring
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 600000
      connection-timeout: 3000
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:  
      # 제발 꼭 update로
      ddl-auto: update
  data:
    redis:
      host: localhost
      port: 6379
  mail:
    host: smtp.gmail.com
    port: 587
    username: luo199829@gmail.com
    password: hsgl yoex mhfa ltzm
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true
  cloud:
    refresh:
      extra-refreshable: com.zaxxer.hikari.HikariDataSource

jwt:
  expiration: 60
  secretKey: rI9KLc/nWq+0ehvbQXjST52lIHi+A4PurdKwAe0ZcN+0LE1QBv7p0qhFx8wzt8PaigtMXpJHdIl6p4ILsLDasA==

  secretKeyRt: rI9KLc/nWq+0ehvbQXjST52lIHi+A4PurdKwAe0ZcN+0LE1QBv7p0qhFx8wzt8PaigtMXpJHdIl6p4ILsLDasA==
  expirationRt: 120

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
      instance:
        instance-id: ${spring.cloud.client.ip-address}:${spring.application.instance_id:${random.value}}

oauth2:
  kakao:
    client-id: # push 전에 꼭 지워주시기 바랍니다!
    redirect-uri: http://localhost:8000/user-service/user/kakao