name: MSA Build & Deploy

on:
  push:
    branches: [ "user" ]

env:
  REGION: ap-northeast-2
  ECR_REGISTRY: 061039771220.dkr.ecr.ap-northeast-2.amazonaws.com
  SERVICE_DIRS: config-service,discovery-service,gateway-service,user-service,postservice,order-service,course-service
  TAG: 1.0.${{ github.run_number }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Check docker-compose.yml existence
        run: ls -l docker-compose.yml

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and Push Docker Images
        run: |
          for service in $(echo "${{ env.SERVICE_DIRS }}" | tr ',' '\n'); do
            echo "Building and pushing $service"
            cd $service
            chmod +x ./gradlew
            ./gradlew clean build -x test
            docker build -t $ECR_REGISTRY/$service:${{ env.TAG }} .
            docker push $ECR_REGISTRY/$service:${{ env.TAG }}
            cd ..
          done

      - name: Copy docker-compose.yml to EC2 home directory
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          source: docker-compose.yml
          target: /home/ubuntu/docker-compose.yml

      - name: SSH Deploy to EC2
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd /home/ubuntu

            # docker-compose 설치 여부 확인 및 없으면 설치
            which docker-compose || (
              echo "docker-compose not found, installing..."
              sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
              sudo chmod +x /usr/local/bin/docker-compose
            )

            aws ecr get-login-password --region ${{ env.REGION }} | docker login --username AWS --password-stdin ${{ env.ECR_REGISTRY }}

            docker-compose down

            docker-compose pull
            docker-compose up -d
