name: MSA Build & Deploy

on:
  push:
    branches: [ "user" ]

env:
  REGION: ap-northeast-2
  ECR_REGISTRY: 061039771220.dkr.ecr.ap-northeast-2.amazonaws.com
  SERVICE_DIRS: config-service,discovery-service,gateway-service,user-service,postservice,order-service,course-service
  TAG: 1.0.${{ github.run_number }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and Push Docker Images
        run: |
          for service in $(echo "${{ env.SERVICE_DIRS }}" | tr ',' '\n'); do
            echo "Building and pushing $service"
            cd $service
            chmod +x ./gradlew
            ./gradlew clean build -x test
            docker build -t $ECR_REGISTRY/$service:${{ env.TAG }} .
            docker push $ECR_REGISTRY/$service:${{ env.TAG }}
            cd ..
          done

      - name: SSH Deploy to EC2 (docker run)
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |
            # ECR 로그인
            aws ecr get-login-password --region ${{ env.REGION }} | docker login --username AWS --password-stdin ${{ env.ECR_REGISTRY }}

            # 이전 컨테이너 정리
            docker rm -f config-service discovery-service gateway-service user-service postservice order-service course-service || true

            # 공통 옵션
            BASE_URL=${{ env.ECR_REGISTRY }}
            TAG=${{ env.TAG }}

            # 서비스별 실행
            docker run -d --name config-service -p 8888:8888 $BASE_URL/config-service:$TAG
            docker run -d --name discovery-service -p 8761:8761 $BASE_URL/discovery-service:$TAG
            docker run -d --name gateway-service -p 8000:8000 --link config-service --link discovery-service $BASE_URL/gateway-service:$TAG
            docker run -d --name user-service -p 8081:8080 $BASE_URL/user-service:$TAG
            docker run -d --name postservice -p 8082:8080 $BASE_URL/postservice:$TAG
            docker run -d --name order-service -p 8083:8080 $BASE_URL/order-service:$TAG
            docker run -d --name course-service -p 8084:8080 $BASE_URL/course-service:$TAG
